### ISSUE TITLE
Ammunition

### ISSUE THREAD

**Issue by Kynuska** [mothball187/TimedProgression#3]
Hello. First of all, thank you for a great job. Once upon a time I played on a server where there was a stone age, a bronze age, etc.
I would like to do something similar.
But when I add "ammunition", the plugin stops working.

			items["Ammunition", "ammo.pistol"] = 2;
			items["Ammunition", "arrow.wooden"] = 3;

In items.json are registered

"Ammunition": {
    "ammo.pistol": 2,
    "arrow.wooden": 3

but the plugin does not work.

Thank Ales.

**Comment by mothball187** [comment]
Thank you for the compliments and for reaching out, @Kynuska ! I think your problem might be that you have the configuration wrong in your example you shared. I would assume you want it like this:

items["Ammunition", "arrow.wooden"] = 1;
items["Ammunition", "ammo.pistol"] = 2;

This would allow arrows in phase 1 and restrict pistol bullets until phase 2. If a player were to loot pistol bullets in phase 1, he instead would loot arrows. Does this make sense?

**Comment by Kynuska** [comment]
This was just an example. Even if I add only one line 
"items [" Ammunition "," ammo.pistol "] = 2;"
 the plugin will stop working. I don't know if it has anything to do with rewriting to heavyammo.

**Comment by Kynuska** [comment]
Please ask. When I add Phase, it doesn't display a list of / listitems commands.
timedprogression.setphase 0 / listiitems - list of phase 2+3
timedprogression.setphase 1 / listiitems - list of phase 2+3
timedprogression.setphase 2 / listiitems - list of phase 3
timedprogression.setphase 3 / listiitems - nothing
timedprogression.setphase 4 / listiitems - All items unlocked!

**Comment by jtbennett-fe** [comment]
I see that you are modifying the C# file (TimedProgression.cs) itself, rather than the items.json file. I cannot support this, because you may have accidentally made a mistake that can break the plugin (this is very easy to do!). I recommend deleting all the plugin files (the TimedProgression.cs file as well as the items.json and configuration json file), and redownloading the plugin file and uploading it to your server to reinstall it.

To make changes to the items and their phases, modify the items.json file and be careful not to break the json syntax. You may want to use a json editor to help with this.

To add or change phases, modify the configuration file and add or modify the numbers in the "thresholds" array.

The "timedprogression.setphase" command does not change your phases configuration, it simply changes the current phase your server is in.

Please read the README file for all these details: https://github.com/mothball187/TimedProgression/blob/master/README.md

**Comment by mothball187** [comment]
I see that you are modifying the C# file (TimedProgression.cs) itself, rather than the items.json file. I cannot support this, because you may have accidentally made a mistake that can break the plugin (this is very easy to do!). I recommend deleting all the plugin files (the TimedProgression.cs file as well as the items.json and configuration json file), and redownloading the plugin file and uploading it to your server to reinstall it.

To make changes to the items and their phases, modify the items.json file and be careful not to break the json syntax. You may want to use a json editor to help with this.

To add or change phases, modify the configuration file and add or modify the numbers in the "thresholds" array.

The "timedprogression.setphase" command does not change your phases configuration, it simply changes the current phase your server is in.

Please read the README file for all these details: https://github.com/mothball187/TimedProgression/blob/master/README.md

**Comment by mothball187** [comment]
Also, if you would like for your Rust server to be advertised on this Github README, feel free to send me the server details and I can add it to the list!

**Comment by Kynuska** [comment]
I am sorry. I'm a jerk. I made it too complicated.
now I have the TimedProgression.cs original without modification.
- / listitems already works
- TimedProgression.json - I added a phase and it works
- but if I add ammunition, the plugin will not start.
I am attaching items.json.

[items.zip](https://github.com/mothball187/TimedProgression/files/5012712/items.zip)

**Comment by mothball187** [comment]
No problem sir :) I found your issue! See line 283, a few of your items are missing commas.

**Comment by Kynuska** [comment]
Thank you for your nerves. I'm already bothering you too much.
I fixed and checked it using Altova XML Spy.
The ammunition file still does not run.
And items from phase 2 still appear in barrels in phase 1 (metalblade, propanetank, ...)
When I pick them up, they decompose.
Otherwise the server is here, but I would not publish it until I have problems.
[server](https://www.fakaheda.eu/prezentace-serveru/326815-czsk-timed-progression-pve)
[items.zip](https://github.com/mothball187/TimedProgression/files/5017271/items.zip)

**Comment by mothball187** [comment]
No worries, I am glad to help as much as I can. As for the barrels holding items they should not be, this is likely because the plugin is not currently checking loot in barrels. This was not something I considered in my design, since I was only concerned with weapons and armor at the time and those do not spawn in barrels. 

I can try to update the plugin to support barrels and I can try to help you troubleshoot the issue with the ammunition config, but I would need your help with some testing since I no longer have a Rust server to test with. If you are interested in working with me, please share an email address I can contact you at.

**Comment by Kynuska** [comment]
I wrote a message on umod.

**Comment by mothball187** [comment]
fixed: https://github.com/mothball187/TimedProgression/commit/b5bf5ef9772d4ec5a254baf30e9ea5a9556c284e
